name: GitHub Actions CI
on:
  push:
    branches: main
  pull_request: []
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Set up PostgreSQL
        run: |
          sudo apt-get install postgresql libpq-dev
          sudo service postgresql start
          sudo -u postgres createuser --superuser "$USER"

      - name: Set up Rails
        run: bin/rails db:setup
        env:
          RAILS_ENV: test

      - name: Run tests
        run: bundle exec rake test

      - name: Run RuboCop
        run: bundle exec rubocop
